/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalRouteImport } from './routes/local'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as ApiPublicWidgetRouteImport } from './routes/api/public/widget'
import { Route as ApiPublicSnapshotRouteImport } from './routes/api/public/snapshot'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as ApiPublicPairStatusRouteImport } from './routes/api/public/pair-status'
import { Route as ApiPublicPairInitRouteImport } from './routes/api/public/pair-init'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicLicenseStatusRouteImport } from './routes/api/public/license-status'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicCommandsRouteImport } from './routes/api/public/commands'
import { Route as ApiPublicActivateRouteImport } from './routes/api/public/activate'
import { Route as ApiAdminSmtpTestRouteImport } from './routes/api/admin/smtp-test'
import { Route as ApiPublicAgentUpdateRouteImport } from './routes/api/public/agent.update'
import { Route as ApiPublicAgentInstallRouteImport } from './routes/api/public/agent.install'
import { Route as ApiPublicAgentAgentRouteImport } from './routes/api/public/agent.agent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetRoute = ApiPublicWidgetRouteImport.update({
  id: '/api/public/widget',
  path: '/api/public/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnapshotRoute = ApiPublicSnapshotRouteImport.update({
  id: '/api/public/snapshot',
  path: '/api/public/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairStatusRoute = ApiPublicPairStatusRouteImport.update({
  id: '/api/public/pair-status',
  path: '/api/public/pair-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairInitRoute = ApiPublicPairInitRouteImport.update({
  id: '/api/public/pair-init',
  path: '/api/public/pair-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseStatusRoute = ApiPublicLicenseStatusRouteImport.update({
  id: '/api/public/license-status',
  path: '/api/public/license-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommandsRoute = ApiPublicCommandsRouteImport.update({
  id: '/api/public/commands',
  path: '/api/public/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActivateRoute = ApiPublicActivateRouteImport.update({
  id: '/api/public/activate',
  path: '/api/public/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSmtpTestRoute = ApiAdminSmtpTestRouteImport.update({
  id: '/api/admin/smtp-test',
  path: '/api/admin/smtp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUpdateRoute = ApiPublicAgentUpdateRouteImport.update({
  id: '/api/public/agent/update',
  path: '/api/public/agent/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentInstallRoute = ApiPublicAgentInstallRouteImport.update({
  id: '/api/public/agent/install',
  path: '/api/public/agent/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAgentRoute = ApiPublicAgentAgentRouteImport.update({
  id: '/api/public/agent/agent',
  path: '/api/public/agent/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/api/admin/smtp-test': typeof ApiAdminSmtpTestRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/pair-init': typeof ApiPublicPairInitRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/snapshot': typeof ApiPublicSnapshotRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/agent/agent': typeof ApiPublicAgentAgentRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/update': typeof ApiPublicAgentUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/api/admin/smtp-test': typeof ApiAdminSmtpTestRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/pair-init': typeof ApiPublicPairInitRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/snapshot': typeof ApiPublicSnapshotRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/agent/agent': typeof ApiPublicAgentAgentRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/update': typeof ApiPublicAgentUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/api/admin/smtp-test': typeof ApiAdminSmtpTestRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/pair-init': typeof ApiPublicPairInitRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/snapshot': typeof ApiPublicSnapshotRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/agent/agent': typeof ApiPublicAgentAgentRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/update': typeof ApiPublicAgentUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/local'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sites/$siteId'
    | '/api/admin/smtp-test'
    | '/api/public/activate'
    | '/api/public/commands'
    | '/api/public/ingest'
    | '/api/public/license-status'
    | '/api/public/manifest'
    | '/api/public/pair-init'
    | '/api/public/pair-status'
    | '/api/public/push-dispatch'
    | '/api/public/register'
    | '/api/public/snapshot'
    | '/api/public/widget'
    | '/api/public/agent/agent'
    | '/api/public/agent/install'
    | '/api/public/agent/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/local'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sites/$siteId'
    | '/api/admin/smtp-test'
    | '/api/public/activate'
    | '/api/public/commands'
    | '/api/public/ingest'
    | '/api/public/license-status'
    | '/api/public/manifest'
    | '/api/public/pair-init'
    | '/api/public/pair-status'
    | '/api/public/push-dispatch'
    | '/api/public/register'
    | '/api/public/snapshot'
    | '/api/public/widget'
    | '/api/public/agent/agent'
    | '/api/public/agent/install'
    | '/api/public/agent/update'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/local'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sites/$siteId'
    | '/api/admin/smtp-test'
    | '/api/public/activate'
    | '/api/public/commands'
    | '/api/public/ingest'
    | '/api/public/license-status'
    | '/api/public/manifest'
    | '/api/public/pair-init'
    | '/api/public/pair-status'
    | '/api/public/push-dispatch'
    | '/api/public/register'
    | '/api/public/snapshot'
    | '/api/public/widget'
    | '/api/public/agent/agent'
    | '/api/public/agent/install'
    | '/api/public/agent/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  LocalRoute: typeof LocalRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  ApiAdminSmtpTestRoute: typeof ApiAdminSmtpTestRoute
  ApiPublicActivateRoute: typeof ApiPublicActivateRoute
  ApiPublicCommandsRoute: typeof ApiPublicCommandsRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicLicenseStatusRoute: typeof ApiPublicLicenseStatusRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicPairInitRoute: typeof ApiPublicPairInitRoute
  ApiPublicPairStatusRoute: typeof ApiPublicPairStatusRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
  ApiPublicSnapshotRoute: typeof ApiPublicSnapshotRoute
  ApiPublicWidgetRoute: typeof ApiPublicWidgetRoute
  ApiPublicAgentAgentRoute: typeof ApiPublicAgentAgentRoute
  ApiPublicAgentInstallRoute: typeof ApiPublicAgentInstallRoute
  ApiPublicAgentUpdateRoute: typeof ApiPublicAgentUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget': {
      id: '/api/public/widget'
      path: '/api/public/widget'
      fullPath: '/api/public/widget'
      preLoaderRoute: typeof ApiPublicWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snapshot': {
      id: '/api/public/snapshot'
      path: '/api/public/snapshot'
      fullPath: '/api/public/snapshot'
      preLoaderRoute: typeof ApiPublicSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair-status': {
      id: '/api/public/pair-status'
      path: '/api/public/pair-status'
      fullPath: '/api/public/pair-status'
      preLoaderRoute: typeof ApiPublicPairStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair-init': {
      id: '/api/public/pair-init'
      path: '/api/public/pair-init'
      fullPath: '/api/public/pair-init'
      preLoaderRoute: typeof ApiPublicPairInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license-status': {
      id: '/api/public/license-status'
      path: '/api/public/license-status'
      fullPath: '/api/public/license-status'
      preLoaderRoute: typeof ApiPublicLicenseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commands': {
      id: '/api/public/commands'
      path: '/api/public/commands'
      fullPath: '/api/public/commands'
      preLoaderRoute: typeof ApiPublicCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activate': {
      id: '/api/public/activate'
      path: '/api/public/activate'
      fullPath: '/api/public/activate'
      preLoaderRoute: typeof ApiPublicActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/smtp-test': {
      id: '/api/admin/smtp-test'
      path: '/api/admin/smtp-test'
      fullPath: '/api/admin/smtp-test'
      preLoaderRoute: typeof ApiAdminSmtpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/update': {
      id: '/api/public/agent/update'
      path: '/api/public/agent/update'
      fullPath: '/api/public/agent/update'
      preLoaderRoute: typeof ApiPublicAgentUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/install': {
      id: '/api/public/agent/install'
      path: '/api/public/agent/install'
      fullPath: '/api/public/agent/install'
      preLoaderRoute: typeof ApiPublicAgentInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/agent': {
      id: '/api/public/agent/agent'
      path: '/api/public/agent/agent'
      fullPath: '/api/public/agent/agent'
      preLoaderRoute: typeof ApiPublicAgentAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  LocalRoute: LocalRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  ApiAdminSmtpTestRoute: ApiAdminSmtpTestRoute,
  ApiPublicActivateRoute: ApiPublicActivateRoute,
  ApiPublicCommandsRoute: ApiPublicCommandsRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicLicenseStatusRoute: ApiPublicLicenseStatusRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicPairInitRoute: ApiPublicPairInitRoute,
  ApiPublicPairStatusRoute: ApiPublicPairStatusRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
  ApiPublicSnapshotRoute: ApiPublicSnapshotRoute,
  ApiPublicWidgetRoute: ApiPublicWidgetRoute,
  ApiPublicAgentAgentRoute: ApiPublicAgentAgentRoute,
  ApiPublicAgentInstallRoute: ApiPublicAgentInstallRoute,
  ApiPublicAgentUpdateRoute: ApiPublicAgentUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
