/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalRouteImport } from './routes/local'
import { Route as AppLoginRouteImport } from './routes/app-login'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApkAuthRouteImport } from './routes/apk-auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesOverviewRouteImport } from './routes/sites.overview'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppWidgetsRouteImport } from './routes/app.widgets'
import { Route as ApiPublicWidgetDataRouteImport } from './routes/api/public/widget-data'
import { Route as ApiPublicWidgetRouteImport } from './routes/api/public/widget'
import { Route as ApiPublicSnapshotRouteImport } from './routes/api/public/snapshot'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as ApiPublicPairStatusRouteImport } from './routes/api/public/pair-status'
import { Route as ApiPublicPairInitRouteImport } from './routes/api/public/pair-init'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicLicenseStatusRouteImport } from './routes/api/public/license-status'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicCommandsRouteImport } from './routes/api/public/commands'
import { Route as ApiPublicApkLoginRouteImport } from './routes/api/public/apk-login'
import { Route as ApiPublicApkLatestRouteImport } from './routes/api/public/apk-latest'
import { Route as ApiPublicApkBrandRouteImport } from './routes/api/public/apk-brand'
import { Route as ApiPublicApkBootstrapRouteImport } from './routes/api/public/apk-bootstrap'
import { Route as ApiPublicActivateRouteImport } from './routes/api/public/activate'
import { Route as ApiAdminSmtpTestRouteImport } from './routes/api/admin/smtp-test'
import { Route as ApiPublicAgentUpdateRouteImport } from './routes/api/public/agent.update'
import { Route as ApiPublicAgentInstallRouteImport } from './routes/api/public/agent.install'
import { Route as ApiPublicAgentAgentRouteImport } from './routes/api/public/agent.agent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app-login',
  path: '/app-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApkAuthRoute = ApkAuthRouteImport.update({
  id: '/apk-auth',
  path: '/apk-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesOverviewRoute = SitesOverviewRouteImport.update({
  id: '/sites/overview',
  path: '/sites/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWidgetsRoute = AppWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWidgetDataRoute = ApiPublicWidgetDataRouteImport.update({
  id: '/api/public/widget-data',
  path: '/api/public/widget-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetRoute = ApiPublicWidgetRouteImport.update({
  id: '/api/public/widget',
  path: '/api/public/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnapshotRoute = ApiPublicSnapshotRouteImport.update({
  id: '/api/public/snapshot',
  path: '/api/public/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairStatusRoute = ApiPublicPairStatusRouteImport.update({
  id: '/api/public/pair-status',
  path: '/api/public/pair-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairInitRoute = ApiPublicPairInitRouteImport.update({
  id: '/api/public/pair-init',
  path: '/api/public/pair-init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseStatusRoute = ApiPublicLicenseStatusRouteImport.update({
  id: '/api/public/license-status',
  path: '/api/public/license-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommandsRoute = ApiPublicCommandsRouteImport.update({
  id: '/api/public/commands',
  path: '/api/public/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApkLoginRoute = ApiPublicApkLoginRouteImport.update({
  id: '/api/public/apk-login',
  path: '/api/public/apk-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApkLatestRoute = ApiPublicApkLatestRouteImport.update({
  id: '/api/public/apk-latest',
  path: '/api/public/apk-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApkBrandRoute = ApiPublicApkBrandRouteImport.update({
  id: '/api/public/apk-brand',
  path: '/api/public/apk-brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApkBootstrapRoute = ApiPublicApkBootstrapRouteImport.update({
  id: '/api/public/apk-bootstrap',
  path: '/api/public/apk-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActivateRoute = ApiPublicActivateRouteImport.update({
  id: '/api/public/activate',
  path: '/api/public/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSmtpTestRoute = ApiAdminSmtpTestRouteImport.update({
  id: '/api/admin/smtp-test',
  path: '/api/admin/smtp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUpdateRoute = ApiPublicAgentUpdateRouteImport.update({
  id: '/api/public/agent/update',
  path: '/api/public/agent/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentInstallRoute = ApiPublicAgentInstallRouteImport.update({
  id: '/api/public/agent/install',
  path: '/api/public/agent/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAgentRoute = ApiPublicAgentAgentRouteImport.update({
  id: '/api/public/agent/agent',
  path: '/api/public/agent/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apk-auth': typeof ApkAuthRoute
  '/app': typeof AppRouteWithChildren
  '/app-login': typeof AppLoginRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/widgets': typeof AppWidgetsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/overview': typeof SitesOverviewRoute
  '/api/admin/smtp-test': typeof ApiAdminSmtpTestRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/apk-bootstrap': typeof ApiPublicApkBootstrapRoute
  '/api/public/apk-brand': typeof ApiPublicApkBrandRoute
  '/api/public/apk-latest': typeof ApiPublicApkLatestRoute
  '/api/public/apk-login': typeof ApiPublicApkLoginRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/pair-init': typeof ApiPublicPairInitRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/snapshot': typeof ApiPublicSnapshotRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/api/public/agent/agent': typeof ApiPublicAgentAgentRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/update': typeof ApiPublicAgentUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apk-auth': typeof ApkAuthRoute
  '/app': typeof AppRouteWithChildren
  '/app-login': typeof AppLoginRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/widgets': typeof AppWidgetsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/overview': typeof SitesOverviewRoute
  '/api/admin/smtp-test': typeof ApiAdminSmtpTestRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/apk-bootstrap': typeof ApiPublicApkBootstrapRoute
  '/api/public/apk-brand': typeof ApiPublicApkBrandRoute
  '/api/public/apk-latest': typeof ApiPublicApkLatestRoute
  '/api/public/apk-login': typeof ApiPublicApkLoginRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/pair-init': typeof ApiPublicPairInitRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/snapshot': typeof ApiPublicSnapshotRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/api/public/agent/agent': typeof ApiPublicAgentAgentRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/update': typeof ApiPublicAgentUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apk-auth': typeof ApkAuthRoute
  '/app': typeof AppRouteWithChildren
  '/app-login': typeof AppLoginRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/widgets': typeof AppWidgetsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/overview': typeof SitesOverviewRoute
  '/api/admin/smtp-test': typeof ApiAdminSmtpTestRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/apk-bootstrap': typeof ApiPublicApkBootstrapRoute
  '/api/public/apk-brand': typeof ApiPublicApkBrandRoute
  '/api/public/apk-latest': typeof ApiPublicApkLatestRoute
  '/api/public/apk-login': typeof ApiPublicApkLoginRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/pair-init': typeof ApiPublicPairInitRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/snapshot': typeof ApiPublicSnapshotRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
  '/api/public/widget-data': typeof ApiPublicWidgetDataRoute
  '/api/public/agent/agent': typeof ApiPublicAgentAgentRoute
  '/api/public/agent/install': typeof ApiPublicAgentInstallRoute
  '/api/public/agent/update': typeof ApiPublicAgentUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/apk-auth'
    | '/app'
    | '/app-login'
    | '/local'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/widgets'
    | '/invite/$token'
    | '/sites/$siteId'
    | '/sites/overview'
    | '/api/admin/smtp-test'
    | '/api/public/activate'
    | '/api/public/apk-bootstrap'
    | '/api/public/apk-brand'
    | '/api/public/apk-latest'
    | '/api/public/apk-login'
    | '/api/public/commands'
    | '/api/public/ingest'
    | '/api/public/license-status'
    | '/api/public/manifest'
    | '/api/public/pair-init'
    | '/api/public/pair-status'
    | '/api/public/push-dispatch'
    | '/api/public/snapshot'
    | '/api/public/widget'
    | '/api/public/widget-data'
    | '/api/public/agent/agent'
    | '/api/public/agent/install'
    | '/api/public/agent/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/apk-auth'
    | '/app'
    | '/app-login'
    | '/local'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/widgets'
    | '/invite/$token'
    | '/sites/$siteId'
    | '/sites/overview'
    | '/api/admin/smtp-test'
    | '/api/public/activate'
    | '/api/public/apk-bootstrap'
    | '/api/public/apk-brand'
    | '/api/public/apk-latest'
    | '/api/public/apk-login'
    | '/api/public/commands'
    | '/api/public/ingest'
    | '/api/public/license-status'
    | '/api/public/manifest'
    | '/api/public/pair-init'
    | '/api/public/pair-status'
    | '/api/public/push-dispatch'
    | '/api/public/snapshot'
    | '/api/public/widget'
    | '/api/public/widget-data'
    | '/api/public/agent/agent'
    | '/api/public/agent/install'
    | '/api/public/agent/update'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/apk-auth'
    | '/app'
    | '/app-login'
    | '/local'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/widgets'
    | '/invite/$token'
    | '/sites/$siteId'
    | '/sites/overview'
    | '/api/admin/smtp-test'
    | '/api/public/activate'
    | '/api/public/apk-bootstrap'
    | '/api/public/apk-brand'
    | '/api/public/apk-latest'
    | '/api/public/apk-login'
    | '/api/public/commands'
    | '/api/public/ingest'
    | '/api/public/license-status'
    | '/api/public/manifest'
    | '/api/public/pair-init'
    | '/api/public/pair-status'
    | '/api/public/push-dispatch'
    | '/api/public/snapshot'
    | '/api/public/widget'
    | '/api/public/widget-data'
    | '/api/public/agent/agent'
    | '/api/public/agent/install'
    | '/api/public/agent/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ApkAuthRoute: typeof ApkAuthRoute
  AppRoute: typeof AppRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  LocalRoute: typeof LocalRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesOverviewRoute: typeof SitesOverviewRoute
  ApiAdminSmtpTestRoute: typeof ApiAdminSmtpTestRoute
  ApiPublicActivateRoute: typeof ApiPublicActivateRoute
  ApiPublicApkBootstrapRoute: typeof ApiPublicApkBootstrapRoute
  ApiPublicApkBrandRoute: typeof ApiPublicApkBrandRoute
  ApiPublicApkLatestRoute: typeof ApiPublicApkLatestRoute
  ApiPublicApkLoginRoute: typeof ApiPublicApkLoginRoute
  ApiPublicCommandsRoute: typeof ApiPublicCommandsRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicLicenseStatusRoute: typeof ApiPublicLicenseStatusRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicPairInitRoute: typeof ApiPublicPairInitRoute
  ApiPublicPairStatusRoute: typeof ApiPublicPairStatusRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicSnapshotRoute: typeof ApiPublicSnapshotRoute
  ApiPublicWidgetRoute: typeof ApiPublicWidgetRoute
  ApiPublicWidgetDataRoute: typeof ApiPublicWidgetDataRoute
  ApiPublicAgentAgentRoute: typeof ApiPublicAgentAgentRoute
  ApiPublicAgentInstallRoute: typeof ApiPublicAgentInstallRoute
  ApiPublicAgentUpdateRoute: typeof ApiPublicAgentUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-login': {
      id: '/app-login'
      path: '/app-login'
      fullPath: '/app-login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apk-auth': {
      id: '/apk-auth'
      path: '/apk-auth'
      fullPath: '/apk-auth'
      preLoaderRoute: typeof ApkAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/overview': {
      id: '/sites/overview'
      path: '/sites/overview'
      fullPath: '/sites/overview'
      preLoaderRoute: typeof SitesOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/widgets': {
      id: '/app/widgets'
      path: '/widgets'
      fullPath: '/app/widgets'
      preLoaderRoute: typeof AppWidgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/widget-data': {
      id: '/api/public/widget-data'
      path: '/api/public/widget-data'
      fullPath: '/api/public/widget-data'
      preLoaderRoute: typeof ApiPublicWidgetDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget': {
      id: '/api/public/widget'
      path: '/api/public/widget'
      fullPath: '/api/public/widget'
      preLoaderRoute: typeof ApiPublicWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snapshot': {
      id: '/api/public/snapshot'
      path: '/api/public/snapshot'
      fullPath: '/api/public/snapshot'
      preLoaderRoute: typeof ApiPublicSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair-status': {
      id: '/api/public/pair-status'
      path: '/api/public/pair-status'
      fullPath: '/api/public/pair-status'
      preLoaderRoute: typeof ApiPublicPairStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair-init': {
      id: '/api/public/pair-init'
      path: '/api/public/pair-init'
      fullPath: '/api/public/pair-init'
      preLoaderRoute: typeof ApiPublicPairInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license-status': {
      id: '/api/public/license-status'
      path: '/api/public/license-status'
      fullPath: '/api/public/license-status'
      preLoaderRoute: typeof ApiPublicLicenseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commands': {
      id: '/api/public/commands'
      path: '/api/public/commands'
      fullPath: '/api/public/commands'
      preLoaderRoute: typeof ApiPublicCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apk-login': {
      id: '/api/public/apk-login'
      path: '/api/public/apk-login'
      fullPath: '/api/public/apk-login'
      preLoaderRoute: typeof ApiPublicApkLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apk-latest': {
      id: '/api/public/apk-latest'
      path: '/api/public/apk-latest'
      fullPath: '/api/public/apk-latest'
      preLoaderRoute: typeof ApiPublicApkLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apk-brand': {
      id: '/api/public/apk-brand'
      path: '/api/public/apk-brand'
      fullPath: '/api/public/apk-brand'
      preLoaderRoute: typeof ApiPublicApkBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apk-bootstrap': {
      id: '/api/public/apk-bootstrap'
      path: '/api/public/apk-bootstrap'
      fullPath: '/api/public/apk-bootstrap'
      preLoaderRoute: typeof ApiPublicApkBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activate': {
      id: '/api/public/activate'
      path: '/api/public/activate'
      fullPath: '/api/public/activate'
      preLoaderRoute: typeof ApiPublicActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/smtp-test': {
      id: '/api/admin/smtp-test'
      path: '/api/admin/smtp-test'
      fullPath: '/api/admin/smtp-test'
      preLoaderRoute: typeof ApiAdminSmtpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/update': {
      id: '/api/public/agent/update'
      path: '/api/public/agent/update'
      fullPath: '/api/public/agent/update'
      preLoaderRoute: typeof ApiPublicAgentUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/install': {
      id: '/api/public/agent/install'
      path: '/api/public/agent/install'
      fullPath: '/api/public/agent/install'
      preLoaderRoute: typeof ApiPublicAgentInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/agent': {
      id: '/api/public/agent/agent'
      path: '/api/public/agent/agent'
      fullPath: '/api/public/agent/agent'
      preLoaderRoute: typeof ApiPublicAgentAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppWidgetsRoute: typeof AppWidgetsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWidgetsRoute: AppWidgetsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ApkAuthRoute: ApkAuthRoute,
  AppRoute: AppRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  LocalRoute: LocalRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesOverviewRoute: SitesOverviewRoute,
  ApiAdminSmtpTestRoute: ApiAdminSmtpTestRoute,
  ApiPublicActivateRoute: ApiPublicActivateRoute,
  ApiPublicApkBootstrapRoute: ApiPublicApkBootstrapRoute,
  ApiPublicApkBrandRoute: ApiPublicApkBrandRoute,
  ApiPublicApkLatestRoute: ApiPublicApkLatestRoute,
  ApiPublicApkLoginRoute: ApiPublicApkLoginRoute,
  ApiPublicCommandsRoute: ApiPublicCommandsRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicLicenseStatusRoute: ApiPublicLicenseStatusRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicPairInitRoute: ApiPublicPairInitRoute,
  ApiPublicPairStatusRoute: ApiPublicPairStatusRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicSnapshotRoute: ApiPublicSnapshotRoute,
  ApiPublicWidgetRoute: ApiPublicWidgetRoute,
  ApiPublicWidgetDataRoute: ApiPublicWidgetDataRoute,
  ApiPublicAgentAgentRoute: ApiPublicAgentAgentRoute,
  ApiPublicAgentInstallRoute: ApiPublicAgentInstallRoute,
  ApiPublicAgentUpdateRoute: ApiPublicAgentUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
