
-- 1) Pairing codes: 6-char alphanumeric codes generated by the local agent
-- so the user can claim a device by entering the code instead of a name.
CREATE TABLE public.pairing_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  hardware_id text NOT NULL,
  inverter_model text,
  inverter_serial text,
  board_model text,
  agent_version text,
  claimed_by_site uuid REFERENCES public.sites(id) ON DELETE SET NULL,
  claimed_by_user uuid,
  claimed_at timestamptz,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 minutes'),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pairing_code_format CHECK (code ~ '^[A-Z0-9]{6}$')
);
CREATE INDEX pairing_codes_hardware_idx ON public.pairing_codes(hardware_id);
CREATE INDEX pairing_codes_unclaimed_idx ON public.pairing_codes(code) WHERE claimed_by_site IS NULL;

ALTER TABLE public.pairing_codes ENABLE ROW LEVEL SECURITY;

-- Authenticated users may look up an unclaimed code (to verify it before claiming),
-- and may see codes they themselves claimed.
CREATE POLICY pairing_select_own_or_unclaimed ON public.pairing_codes
  FOR SELECT TO authenticated
  USING (claimed_by_user = auth.uid() OR claimed_by_site IS NULL);

-- All write operations are done via service-role server endpoints; no direct
-- INSERT/UPDATE/DELETE policies for ordinary users.

-- 2) Persist a human-readable location label that never changes after the
-- user picks an address (no more silent overwrite by reverse-geocode).
ALTER TABLE public.pv_system_config
  ADD COLUMN IF NOT EXISTS location_label text;

-- 3) Allow renaming a site at any time (already covered by RLS sites_update_owner_or_admin).
-- No structural change needed.
