// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const fail = (message: string): never => {
      throw new Error(message)
    }
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      fail(message)
    }
    
    const request = getRequest();

    if (!request?.headers) {
      fail('Unauthorized: No request headers available')
    }

    const rawAuthHeader = request.headers.get('authorization');
    const authHeader = rawAuthHeader ?? fail('Unauthorized: No authorization header provided')

    if (!authHeader.startsWith('Bearer ')) {
      fail('Unauthorized: Only Bearer tokens are supported')
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      fail('Unauthorized: No token provided')
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    const claimsData = data?.claims

    if (error || !claimsData) {
      fail('Unauthorized: Invalid token')
    }
    const claims = claimsData ?? fail('Unauthorized: Invalid token')

    if (!claims.sub) {
      fail('Unauthorized: No user ID found in token')
    }

    return next({
      context: {
        supabase,
        userId: claims.sub,
        claims,
      },
    })
  }
)
